#!/usr/bin/bash


user=`users | cut -d" " -f1`


sudo systemctl stop KYGnus_Map.service
sudo systemctl disable KYGnus_Map.service

APP_DIR=/home/$user/Apps
if [ -d "$APP_DIR" ]; then
    sudo rm -rf  mkdir /home/$user/Apps
else
    true
fi



sudo rm -rf /etc/systemd/system/KYGnus_Map.service
sudo rm -rf /etc/KYGnus_Map/
sudo rm -rf /var/log/KYGnus_Map

sudo iptables -F
